#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/orcl
#    username: juanEstevez
#    password: Poolsami1
#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: update
#  sql.init.mode: always


# MySQL Connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quileia
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
cors.path: http://localhost