spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: juanEstevez
    password: Poolsami1
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  sql.init.mode: always

cors.path: http://localhost