DELETE FROM APPOINTMENT WHERE ID_APPOINTMENT = 9;
DELETE FROM APPOINTMENT WHERE ID_APPOINTMENT = 8;
DELETE FROM DOCTOR WHERE ID_DOCTOR = 10;
DELETE FROM DOCTOR WHERE ID_DOCTOR = 11;
DELETE FROM DOCTOR WHERE ID_DOCTOR = 3;
DELETE FROM DOCTOR WHERE ID_DOCTOR = 4;
DELETE FROM PATIENT WHERE ID_PATIENT = 333;
DELETE FROM PATIENT WHERE ID_PATIENT = 334;