DELETE FROM APPOINTMENT WHERE ID_APPOINTMENT = 15;
DELETE FROM APPOINTMENT WHERE ID_APPOINTMENT = 16;
DELETE FROM DOCTOR WHERE ID_DOCTOR = 10;
DELETE FROM DOCTOR WHERE ID_DOCTOR = 11;
DELETE FROM PATIENT WHERE ID_PATIENT = 30;
DELETE FROM PATIENT WHERE ID_PATIENT = 38;