INSERT INTO PATIENT (ID_PATIENT, CLINIC_HISTORY, DATE_OF_BIRTH, EPS, ID_TYPE, NAME) VALUES ('333', 'OK', '2001-10-12', 'Medimas', 'CC', 'Name Test');
INSERT INTO PATIENT (ID_PATIENT, CLINIC_HISTORY, DATE_OF_BIRTH, EPS, ID_TYPE, NAME) VALUES ('334', 'OK', '2001-10-12', 'Medimas2', 'CC', 'Name Test2');
