# MySQL Connection
# MySQL Connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quileia
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
cors.path: http://localhost

# Oracle Connection
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/orcl
#    username: juanEstevez
#    password: oolsami1
#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: update
#  sql.init.mode: always
    
# H2 Connection
#spring.datasource.url=jdbc:h2:mem:quileia
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=false

# PostgreSQL Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=Poolsami1
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.hbm2ddl.auto=update